# Generated by Django 2.1.4 on 2019-06-02 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uphone', models.CharField(max_length=30, verbose_name='聯繫方式')),
                ('upass', models.CharField(max_length=50)),
                ('uemail', models.EmailField(max_length=254, verbose_name='信箱')),
                ('uname', models.CharField(max_length=30, null=True, verbose_name='用戶名')),
                ('isActive', models.BooleanField(default=True, verbose_name='啟用')),
            ],
            options={
                'verbose_name': '用戶名',
                'verbose_name_plural': '用戶名',
                'db_table': 'users',
            },
        ),
    ]
